name: Test script

on: workflow_dispatch

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install git+https://github.com/LyQuid12/arithmos-cipher
    - name: Testing script
      run: |
        arithmos encrypt test TEST 123
        arithmos decrypt 5663606157 20051920 46314546
        python ./examples/chain.py
